// Generates src/renderer/src/lib/emoji/emoji-data.ts from Unicode's official
// emoji-test.txt (https://unicode.org/Public/emoji/latest/emoji-test.txt).
//
// The output is the full Notion-style catalog, filtered for glyphs that render
// natively and consistently on ALL THREE OSes (Apple Color Emoji / Segoe UI
// Emoji / Noto Color Emoji):
//   • version cap ≤ MAX_EMOJI_VERSION — newer emoji tofu on OS emoji fonts
//     that haven't shipped them yet (Windows lags Unicode by years),
//   • country/subdivision flags excluded — Segoe UI Emoji renders regional
//     indicators as letter pairs, not flags (a famous Windows gap),
//   • skin-tone/ZWJ tone variants excluded — the grid shows base glyphs
//     (same as Notion's grid; tones would multiply the list ~6×),
//   • fully-qualified sequences only.
//
// Usage:  node scripts/emoji/generate.mjs <path-to-emoji-test.txt>
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const MAX_EMOJI_VERSION = 14.0
const EXCLUDED_GROUPS = new Set(['Component'])
const EXCLUDED_SUBGROUPS = new Set(['country-flag', 'subdivision-flag'])

const input = process.argv[2]
if (!input) {
  console.error('usage: node scripts/emoji/generate.mjs <path-to-emoji-test.txt>')
  process.exit(1)
}
const lines = fs.readFileSync(input, 'utf8').split('\n')

/** @type {Array<{ label: string; emojis: Array<[string, string]> }>} */
const groups = []
let currentGroup = null
let currentSubgroup = ''
const seen = new Set()

const ENTRY = /^([0-9A-F ]+?)\s*;\s*fully-qualified\s*#\s*(\S+)\s+E(\d+\.\d+)\s+(.+)$/

for (const line of lines) {
  const groupMatch = /^# group: (.+)$/.exec(line)
  if (groupMatch) {
    const label = groupMatch[1].trim()
    currentGroup = EXCLUDED_GROUPS.has(label) ? null : { label, emojis: [] }
    if (currentGroup) groups.push(currentGroup)
    continue
  }
  const subgroupMatch = /^# subgroup: (.+)$/.exec(line)
  if (subgroupMatch) {
    currentSubgroup = subgroupMatch[1].trim()
    continue
  }
  if (!currentGroup || EXCLUDED_SUBGROUPS.has(currentSubgroup)) continue
  const m = ENTRY.exec(line)
  if (!m) continue
  const [, , glyph, version, name] = m
  if (parseFloat(version) > MAX_EMOJI_VERSION) continue
  if (/skin tone/i.test(name)) continue
  if (seen.has(glyph)) continue
  seen.add(glyph)
  currentGroup.emojis.push([glyph, name.trim().toLowerCase()])
}

const kept = groups.filter((g) => g.emojis.length > 0)
const total = kept.reduce((n, g) => n + g.emojis.length, 0)

const header =
  `// GENERATED by scripts/emoji/generate.mjs from Unicode emoji-test.txt — do not edit by hand.\n` +
  `// Full native-emoji catalog, capped at Emoji ${MAX_EMOJI_VERSION.toFixed(1)} and filtered for\n` +
  `// cross-OS rendering (no country flags, no tone variants). ${total} emoji.\n\n` +
  `export type EmojiEntry = readonly [emoji: string, name: string]\n\n` +
  `export const EMOJI_GROUPS: ReadonlyArray<{\n  readonly label: string\n  readonly emojis: ReadonlyArray<EmojiEntry>\n}> = `

const body = JSON.stringify(
  kept.map((g) => ({ label: g.label, emojis: g.emojis })),
  null,
  0
)

const outPath = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
  'src',
  'renderer',
  'src',
  'lib',
  'emoji',
  'emoji-data.ts'
)
fs.mkdirSync(path.dirname(outPath), { recursive: true })
fs.writeFileSync(outPath, `${header}${body}\n`)
console.log(`${outPath}: ${kept.length} groups, ${total} emoji, ${body.length} bytes`)
